name: DotNet Analyzers

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Run .NET Analyzers
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore .NET dependencies
        run: dotnet restore linuxblox.csproj

      - name: Build with .NET Analyzers
        run: dotnet build --no-restore --configuration Release /p:EnableNETAnalyzers=true /p:AnalysisLevel=latest-All /p:TreatWarningsAsErrors=true linuxblox.csproj
